openapi: 3.0.0
info:
  title: Pollen8 API
  version: 1.0.0
  description: Professional networking platform with verified connections
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000
    description: Development
  - url: https://api-staging.pollen8.com
    description: Staging
  - url: https://api.pollen8.com
    description: Production

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        phoneNumber:
          type: string
        industries:
          type: array
          items:
            type: string
        interests:
          type: array
          items:
            type: string
        location:
          $ref: '#/components/schemas/Location'
        networkValue:
          type: number
        connectionCount:
          type: integer
    
    Connection:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        connectedUserId:
          type: string
        connectedAt:
          type: string
          format: date-time
        sharedIndustries:
          type: array
          items:
            type: string
    
    Invite:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        url:
          type: string
        clickCount:
          type: integer
        dailyClicks:
          type: object
          additionalProperties:
            type: integer
    
    Industry:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    
    Interest:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
    
    Location:
      type: object
      properties:
        city:
          type: string
        zipCode:
          type: string
    
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

paths:
  /auth/verify:
    post:
      summary: Initiate phone verification
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNumber:
                  type: string
      responses:
        '200':
          description: Verification initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  verificationId:
                    type: string
        '400':
          description: Invalid phone number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/confirm:
    post:
      summary: Confirm verification code
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                verificationId:
                  type: string
                code:
                  type: string
      responses:
        '200':
          description: Verification successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Invalid verification code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /user/profile:
    get:
      summary: Get user profile
      tags:
        - User
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  networkValue:
                    type: number
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      summary: Update user profile
      tags:
        - User
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                industries:
                  type: array
                  items:
                    type: string
                interests:
                  type: array
                  items:
                    type: string
                location:
                  $ref: '#/components/schemas/Location'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /network/connections:
    get:
      summary: Get user connections
      tags:
        - Network
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Connections retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  connections:
                    type: array
                    items:
                      $ref: '#/components/schemas/Connection'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /network/value:
    get:
      summary: Get network value
      tags:
        - Network
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Network value retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  networkValue:
                    type: number
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /invite:
    post:
      summary: Create invite link
      tags:
        - Invite
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Invite created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invite'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    get:
      summary: Get user invites
      tags:
        - Invite
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Invites retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  invites:
                    type: array
                    items:
                      $ref: '#/components/schemas/Invite'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /invite/{inviteId}/analytics:
    get:
      summary: Get invite analytics
      tags:
        - Invite
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: inviteId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Invite analytics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invite'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Invite not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'