global:
  resolve_timeout: 5m
  smtp_from: alertmanager@pollen8.com
  smtp_smarthost: smtp.pollen8.com:587
  smtp_auth_username: '{{ smtp_username }}'
  smtp_auth_password: '{{ smtp_password }}'
  slack_api_url: '{{ slack_webhook_url }}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-pollen8'
  routes:
    - match:
        severity: 'critical'
      receiver: 'team-pollen8-pager'
    - match:
        severity: 'warning'
      receiver: 'team-pollen8-email'

receivers:
  - name: 'team-pollen8'
    slack_configs:
      - channel: '#monitoring'
        send_resolved: true

  - name: 'team-pollen8-pager'
    pagerduty_configs:
      - service_key: '{{ pagerduty_key }}'

  - name: 'team-pollen8-email'
    email_configs:
      - to: 'team@pollen8.com'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

templates:
  - '/etc/alertmanager/template/*.tmpl'

# Time windows for grouping and repeat intervals
# group_wait: 30s
# group_interval: 5m
# repeat_interval: 4h

# Severity levels and corresponding actions
# Critical: PagerDuty (Immediate response)
# Warning: Email (Response within 4 hours)
# Info: Slack (Best effort response)

# Security considerations:
# - All sensitive values are templated ({{ }}) for secure deployment
# - SMTP uses authentication and TLS
# - Webhook URLs are secured and rotated regularly