version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_SOCKET_URL=ws://localhost:3001
    ports:
      - "5173:5173"
    networks:
      - pollen8-dev-network

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./src/api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/pollen8_dev
    networks:
      - pollen8-dev-network

  socket:
    build:
      context: ./src/socket
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./src/socket:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    networks:
      - pollen8-dev-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - pollen8-dev-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - pollen8-dev-network

volumes:
  mongodb_dev_data:
    name: mongodb_dev_data
  redis_dev_data:
    name: redis_dev_data

networks:
  pollen8-dev-network:
    name: pollen8-dev-network